@api = http://localhost:5000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlYTJmNjVjOTc4OTE0NTNkYWVhNjBmODQ5OGJlMjg3NiIsInVuaXF1ZV9uYW1lIjoiZWEyZjY1Yzk3ODkxNDUzZGFlYTYwZjg0OThiZTI4NzYiLCJqdGkiOiIwZDYxNGFmMC05NWJkLTRlZmMtODk3NS0xNzAwMGQ5OGY1MzkiLCJpYXQiOiIxNTYyMTAxMTE1NTIxIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoidXNlciIsIm5iZiI6MTU2MjEwMTExNSwiZXhwIjoxNTYyMTA0NzE1LCJpc3MiOiJwYWNjbyJ9.nfDrNWLRdED-j3f3hPoB_rIj00BoHcSRazmg-QBS_Qo

# ============== IDENTITY ==================== #

### POST sign-up
POST {{api}}/identity/sign-up
Content-Type: application/json

{
  "email": "user1@test.com",
  "password": "secret",
  "role": "user"
}

### POST sign-in
POST {{api}}/identity/sign-in
Content-Type: application/json

{
  "email": "user1@test.com",
  "password": "secret"
}

### GET me
GET {{api}}/identity/me
Authorization: Bearer {{token}}


# ============== CUSTOMERS ==================== #

### GET customers/me
GET {{api}}/customers/me
Authorization: Bearer {{token}}


### GET customers (admin)
GET {{api}}/customers
Authorization: Bearer {{token}}


### POST customers
POST {{api}}/customers
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "fullName": "John Doe",
  "address": "New York"
}