@api = http://localhost:5000
@accessToken = xxx.xxx.xxx
@customerId = 00000000-0000-0000-0000-000000000000
@parcelId = 00000000-0000-0000-0000-000000000000
@orderId = 00000000-0000-0000-0000-000000000000
@vehicleId = 00000000-0000-0000-0000-000000000000
@operationId = 00000000-0000-0000-0000-000000000000

# ============== IDENTITY ==================== #

### POST sign-up
POST {{api}}/identity/sign-up
Content-Type: application/json

{
  "email": "pacco-user1@mailinator.com",
  "password": "secret",
  "role": "user"
}

### POST sign-in
POST {{api}}/identity/sign-in
Content-Type: application/json

{
  "email": "pacco-user1@mailinator.com",
  "password": "secret"
}

### GET me
GET {{api}}/identity/me
Authorization: Bearer {{accessToken}}


# ============== CUSTOMERS ==================== #

### GET customers/me
GET {{api}}/customers/me
Authorization: Bearer {{accessToken}}


### GET customers (admin)
GET {{api}}/customers
Authorization: Bearer {{accessToken}}


### POST customers
POST {{api}}/customers
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "fullName": "John Doe",
  "address": "New York"
}

# ============== AVAILABILITY ==================== #



# ============== DELIVERIES ==================== #



# ============== OPERATIONS ==================== #

###
GET {{api}}/operations/{{operationId}}

# ============== ORDERS ==================== #

###
GET {{api}}/orders
Authorization: Bearer {{accessToken}}

###
GET {{api}}/orders/{{orderId}}
Authorization: Bearer {{accessToken}}

###
POST {{api}}/orders
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
}

###
DELETE {{api}}/orders/{{orderId}}
Authorization: Bearer {{accessToken}}

###
POST {{api}}/orders/{{orderId}}/parcels
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "orderId": "{{orderId}}",
  "parcelId": "{{parcelId}}"
}

###
POST {{api}}/orders/{{orderId}}/vehicles
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "orderId": "{{orderId}}",
  "vehicleId": "{{vehicleId}}"
}

###
DELETE {{api}}/orders/{{orderId}}/parcels/{{parcelId}}
Authorization: Bearer {{accessToken}}

# ============== PARCELS ==================== #

###
GET {{api}}/parcels
Authorization: Bearer {{accessToken}}

###
GET {{api}}/parcels/{{parcelId}}
Authorization: Bearer {{accessToken}}

###
POST {{api}}/parcels
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "variant": "weapon",
  "size": "large",
  "name": "Parcel #1",
  "description": "My parcel #1"
}

###
DELETE {{api}}/parcels/{{parcelId}}
Authorization: Bearer {{accessToken}}

# ============== PRICING ==================== #



# ============== VEHICLES ==================== #