@api = http://localhost:5000
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNjA5MzNiZmRhMzA0NDM0YjJiOGM0NmE0NjhhNDhjNyIsInVuaXF1ZV9uYW1lIjoiMTYwOTMzYmZkYTMwNDQzNGIyYjhjNDZhNDY4YTQ4YzciLCJqdGkiOiI4ZWQzMjA5My03YjhiLTQ4YWQtYTczOS02NDZjNjMzZTVmYjQiLCJpYXQiOiIxNTYyNDIzODI3NzYxIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoidXNlciIsIm5iZiI6MTU2MjQyMzgyNywiZXhwIjoxNTYyNDI3NDI3LCJpc3MiOiJwYWNjbyJ9.OUO0WtBlwZHmvUZwTlwCWDO-k9dYa645yruaDoUjgMw
@customerId = 00000000-0000-0000-0000-000000000000
@operationId = 00000000-0000-0000-0000-000000000000
@parcelId = 00000000-0000-0000-0000-000000000000
@orderId = 00000000-0000-0000-0000-000000000000
@vehicleId = 00000000-0000-0000-0000-000000000000
@resourceId = 00000000-0000-0000-0000-000000000000
@deliveryId = 00000000-0000-0000-0000-000000000000
@dateTime = 2019-10-10
@deliveryDate = 2019-10-10
@orderPrice = 100


# ============== IDENTITY ==================== #

### POST sign-up
POST {{api}}/identity/sign-up
Content-Type: application/json

{
  "email": "pacco-user1@mailinator.com",
  "password": "secret",
  "role": "user"
}

### POST sign-in
POST {{api}}/identity/sign-in
Content-Type: application/json

{
  "email": "pacco-user1@mailinator.com",
  "password": "secret"
}

### GET me
GET {{api}}/identity/me
Authorization: Bearer {{accessToken}}


# ============== CUSTOMERS ==================== #

### GET customers/me
GET {{api}}/customers/me
Authorization: Bearer {{accessToken}}


### GET customers (admin)
GET {{api}}/customers
Authorization: Bearer {{accessToken}}


### POST customers
POST {{api}}/customers
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "fullName": "John Doe",
  "address": "New York"
}

# ============== AVAILABILITY ==================== #

###
GET {{api}}/availability/resources/{{resourceId}}
Authorization: Bearer {{accessToken}}

###
POST {{api}}/availability/resources
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "id": "{{resourceId}}"
}

###
POST {{api}}/availability/resources/{{resourceId}}/reservations
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "dateTime": "{{dateTime}}",
  "priority": 0
}

###
DELETE {{api}}/availability/resources/{{resourceId}}/reservations/{{dateTime}}
Authorization: Bearer {{accessToken}}

###
DELETE {{api}}/availability/resources/{{resourceId}}
Authorization: Bearer {{accessToken}}

# ============== DELIVERIES ==================== #

###
GET {{api}}/deliveries/{{orderId}}
Authorization: Bearer {{accessToken}}

###
POST {{api}}/deliveries
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "orderId": "{{orderId}}",
  "description": "Delivery description",
  "dateTime": "2019-10-10"
}

###
POST {{api}}/deliveries/{{deliveryId}}/fail
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "id": "{{deliveryId}}",
  "reason": "Delivery failed"
}

###
POST {{api}}/deliveries/{{deliveryId}}/complete
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "id": "{{deliveryId}}"
}

###
POST {{api}}/deliveries/{{deliveryId}}/registrations
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "id": "{{deliveryId}}",
  "description": "Delivery registration description",
  "dateTime": "2019-10-10"
}

# ============== OPERATIONS ==================== #

###
GET {{api}}/operations/{{operationId}}

# ============== ORDERS ==================== #

###
GET {{api}}/orders
Authorization: Bearer {{accessToken}}

###
GET {{api}}/orders/{{orderId}}
Authorization: Bearer {{accessToken}}

###
POST {{api}}/orders
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
}

###
DELETE {{api}}/orders/{{orderId}}
Authorization: Bearer {{accessToken}}

###
POST {{api}}/orders/{{orderId}}/parcels/{{parcelId}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
}

###
POST {{api}}/orders/{{orderId}}/vehicles/{{vehicleId}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "deliveryDate": "{{deliveryDate}}"
}

###
DELETE {{api}}/orders/{{orderId}}/parcels/{{parcelId}}
AuthorizatiOrderDiscountPriceon: Bearer {{accessToken}}

# ============== PARCELS ==================== #

###
GET {{api}}/parcels
Authorization: Bearer {{accessToken}}

###
GET {{api}}/parcels/{{parcelId}}
Authorization: Bearer {{accessToken}}

###
GET {{api}}/parcels/volume?parcelIds=["{{parcelId}}"]
Authorization: Bearer {{accessToken}}

###
POST {{api}}/parcels
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "variant": "weapon",
  "size": "large",
  "name": "Parcel #1",
  "description": "My parcel #1"
}

###
DELETE {{api}}/parcels/{{parcelId}}
Authorization: Bearer {{accessToken}}

# ============== PRICING ==================== #

###
GET {{api}}/pricing?orderPrice={{orderPrice}}
Authorization: Bearer {{accessToken}}

# ============== VEHICLES ==================== #

###
GET {{api}}/vehicles?payloadCapacity=0&loadingCapacity=0&variants=1
Authorization: Bearer {{accessToken}}

###
GET {{api}}/vehicles/{{vehicleId}}
Authorization: Bearer {{accessToken}}

###
POST {{api}}/vehicles
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "brand": "Brand",
  "model": "Model",
  "description": "Vehicle description",
  "payloadCapacity": 1000,
  "loadingCapacity": 1000,
  "pricePerService": 100,
  "variants": 1
}

###
PUT {{api}}/vehicles/{{vehicleId}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "id": "{{vehicleId}}",
  "description": "Updated vehicle description",
  "pricePerService": 150,
  "variants": 2
}

###
DELETE {{api}}/vehicles/{{vehicleId}}